In [1]:
import numpy as np

## MEMBUAT *ndarray*

In [2]:
angka = np.array([10, 20, 30, 40])

print(angka)

[10 20 30 40]


---

## CEK TIPE DATA *ndarray*

In [3]:
print(type(angka))

<class 'numpy.ndarray'>


---

## *ndarray* 1 DIMENSI 

In [8]:
print(np.array([1, 2, 3]))

[1 2 3]


---

## *ndarray* 2 DIMENSI 

In [18]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(a)

[[1 2 3]
 [4 5 6]]


---

## *ndarray* 3 DIMENSI

In [19]:
a = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


---

## OPERASI VECTOR *ndarray* 

In [17]:
a = np.array([1, 2, 3, 4, 5])

#penjumlahan vektor
print(a + 2)

#pengurangan vektor
print(a-2)

#perkalian vektor
print(a*2)

#pembagian vektor
print(a/2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


---
## MEMBUAT *array numpy*

```python
np.array()	   #Mengubah list menjadi ndarray
np.arange()	   #Membuat array dengan selang tertentu
np.linspace()  #Membuat array dengan jumlah titik tertentu
np.zeros()	   #Array berisi nol
np.ones()	   #Array berisi satu
np.empty()	   #Array kosong (nilai awal acak/tidak diinisialisasi)
np.eye()	   #Matriks identitas
np.random	   #Membuat data acak
```
---

## **np.arrange()**

```python
np.arange()
#mirip sekali dengan range()
```

sintaks:
```python
np.arange(start, stop, step)
```
---

In [28]:
#contoh
array = np.arange(5)
print(array)
array1 = np.arange(2, 8)
print(array1)
array2 = np.arange(2, 20, 3)
print(array2)

#jadi yang masuk dalam parameter arange merupakan elemen array  

[0 1 2 3 4]
[2 3 4 5 6 7]
[ 2  5  8 11 14 17]


---
## **np.linspace()**

```python
np.linspace()
```

sintaks:

````python
np.linspace(start, stop, jumlah_data)
````
```text
Perhatikan, parameter ketiga adalah jumlah elemen, bukan langkah (`step`)
```
---

In [34]:
#contoh
lin = np.linspace(0, 10, 5)
print(lin)

[ 0.   2.5  5.   7.5 10. ]


---

## **np.reshape()**

## Apa itu `reshape()`?

`reshape()` digunakan untuk **mengubah bentuk (shape) sebuah array** tanpa mengubah isi datanya.

Contohnya, kamu punya array 1 dimensi:

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

print(arr)
```

Output:

```text
[1 2 3 4 5 6]
```

Dengan `reshape()`, kita bisa mengubahnya menjadi array 2 dimensi.

---

## Bentuk Dasar

Sintaks:

```python
array.reshape(baris, kolom)
```

Contoh:

```python
arr = np.array([1, 2, 3, 4, 5, 6])

hasil = arr.reshape(2, 3)

print(hasil)
```

Output:

```text
[[1 2 3]
 [4 5 6]]
```

Sekarang `shape`-nya berubah.

```python
print(hasil.shape)
```

Output:

```text
(2, 3)
```

---

## Contoh Lain

### Menjadi 3 × 2

```python
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr.reshape(3, 2))
```

Output:

```text
[[1 2]
 [3 4]
 [5 6]]
```

Perhatikan bahwa **isinya tetap sama**, hanya tata letaknya yang berubah.

---

## Menggunakan `arange()`

Ini adalah kombinasi yang paling sering dipakai.

```python
arr = np.arange(1, 13)

print(arr)
```

Output:

```text
[ 1  2  3  4  5  6  7  8  9 10 11 12]
```

Ubah menjadi 3 × 4:

```python
mat = arr.reshape(3, 4)

print(mat)
```

Output:

```text
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
```

Inilah pola yang paling sering kamu lihat di tutorial NumPy.

---

## Syarat Penting

Jumlah elemen **harus tetap sama**.

Misalnya:

```python
arr = np.arange(1, 13)
```

Jumlah elemennya:

```text
12
```

Maka bentuk yang boleh antara lain:

* `(2, 6)`
* `(3, 4)`
* `(4, 3)`
* `(6, 2)`
* `(12, 1)`
* `(1, 12)`

Karena semuanya memiliki:

```text
baris × kolom = 12
```

---

## Contoh Salah

```python
arr = np.arange(1, 13)

arr.reshape(5, 3)
```

Hasilnya:

```text
ValueError:
cannot reshape array of size 12 into shape (5,3)
```

Karena:

```text
5 × 3 = 15
```

Sedangkan array hanya memiliki **12 elemen**.

---

## Menggunakan `-1`

NumPy bisa menghitung salah satu dimensi secara otomatis.

Misalnya:

```python
arr = np.arange(1, 13)

print(arr.reshape(3, -1))
```

Output:

```text
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
```

Kenapa menjadi `(3, 4)`?

Karena:

```text
12 ÷ 3 = 4
```

Contoh lain:

```python
print(arr.reshape(-1, 2))
```

Output:

```text
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
```

NumPy menghitung sendiri bahwa jumlah barisnya adalah `6`.

> **Catatan:** Hanya **satu** dimensi yang boleh menggunakan `-1`.

---

## Ringkasan

| Kode             | Hasil                   |
| ---------------- | ----------------------- |
| `reshape(2, 3)`  | 2 baris, 3 kolom        |
| `reshape(3, 2)`  | 3 baris, 2 kolom        |
| `reshape(-1, 2)` | Baris dihitung otomatis |
| `reshape(3, -1)` | Kolom dihitung otomatis |

---

## Tips Mentor 💡

Gunakan satu aturan sederhana setiap kali memakai `reshape()`:

> **Jumlah elemen sebelum `reshape()` harus sama dengan jumlah elemen sesudah `reshape()`.**

Jika aturan ini terpenuhi, maka `reshape()` hampir selalu akan berhasil.


---
Hasilnya seperti itu karena NumPy diminta membuat 5 angka yang tersebar merata dari `0 sampai 10` (termasuk nilai 10).

Urutannya Menjadi:
```MySQL
0 ----- 2.5 ----- 5 ----- 7.5 ----- 10
```
---

#### Kapan memakai `arange()`?
Kalau kita tahu step.

Misalnya 
> setiap 5 menit
```python
np.arange(0, 61, 5)
```
outputnya:
```text
[ 0  5 10 15 20 25 30 35 40 45 50 55 60]
```


#### Kapan memakai `linspace()`?
Kalau kita tahu ingin membuat berapa titik.

Misalnya:
> bagi garis menjadi 100 titik
```python
np.linspace(0, 1, 100)
```
outputnya:
```text
[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.8989899
 0.90909091 0.91919192 0.92929293 0.93939394 0.94949495 0.95959596
 0.96969697 0.97979798 0.98989899 1.        ]
 ```
 ---

## **np.zeros()**

Sesuai namanya, fungsi ini membuat sebuah array yang semua elemennya bernilai 0

### Array 1 Dimensi

In [47]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


### Array 2 Dimensi
Kalau ingin membuat matriks, masukkan tuple .

In [51]:
print(np.zeros((3, 4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Mengubah Tipe Data 
Misalnya ingin integer

In [53]:
print(np.zeros((2, 3), dtype = int))

[[0 0 0]
 [0 0 0]]


`dtype` = data type 

---

## **np.ones()**

Hampir sama persis.

Bedanya hanya nilai awalnya 1.

In [55]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


### Matriks

In [57]:
print(np.ones((2, 4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Integer

In [63]:
print(np.ones((3, 2), dtype=int))

[[1 1]
 [1 1]
 [1 1]]


---

## **np.empty()**

Nama fungsi ini sering menyesatkan.

Banyak pemula mengira `empty()` berarti array kosong.

Padahal bukan.

`np.empty()` membuat array dengan ukuran tertentu tetapi **tidak menginisialisasi nilainya.**

Artinya, NumPy hanya memesan memori tanpa mengisi dengan 0 atau 1.

In [65]:
#contoh
print(np.empty(5))

[1. 1. 1. 1. 1.]


---

## **np.eye()**

`eye` berasal dari Identity Matrix.

Matriks identitas adalah matriks persegi yang:

- diagonal utama = 1
- sisanya = 0

In [69]:
#contoh
print(np.eye(3, dtype = int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### Kenapa Penting?

Dalam matematika:

Misalnya

```copy
A × I = A
```
dengan

- A = matriks apa pun
- I = identity matrix

Artinya mengalikan dengan matriks identitas tidak mengubah isi matriks.

Mirip seperti:

```copy
10 × 1 = 10
```

Karena itu identity matrix sering disebut sebagai angka 1 versi matriks.

Konsep ini akan muncul lagi saat belajar Linear Algebra, salah satu fondasi Machine Learning.

---

## **np.random()**

Ini adalah modul untuk menghasilkan data acak.

Ada banyak fungsi, tapi kita mulai dari yang paling penting.

### **`randint()`**

### Bilangan bulat acak.

In [80]:
print(np.random.randint(1,10))

4


Karena acak.
> Ingat: batas atas (`high`) tidak termasuk

### Banyak Angka Sekaligus

In [81]:
print(np.random.randint(1,10,5))

[7 3 5 9 7]


### **`rand()`**

Menghasilkan angka acak desimal antara 0 dan 1.

In [83]:
print(np.random.rand(5))

[0.28560706 0.32068876 0.55728934 0.02911257 0.70885171]


### Matriks Acak

In [88]:
print(np.random.rand(2, 3))

[[0.50484567 0.51490677 0.36108651]
 [0.39483206 0.2375345  0.64776753]]


### Kenapa Random Penting?

Dalam Data Science, data acak digunakan untuk:

- membuat data simulasi,
- membagi dataset menjadi train/test,
- inisialisasi parameter model,
- sampling,
- eksperimen.

Jadi `np.random()` adalah salah satu bagian NumPy yang paling sering dipakai.

# Ringkasan Modul 1.1 Fungsi Membuat Array

| Fungsi | Kegunaan |
|---|---|
| `np.array()` | Membuat ndarray dari list |
| `np.arange()` | Berdaasarkan Step |
| `np.linspace()` | Berdsarkan jumlah elemen |
| `np.zeros()` | Semua elemen 0 |
| `np.ones()` | Semua elemen 1 |
| `np.empty()` | Array tanpa inisiasi nilai |
| `np.eye()` | Matriks Identitas |
| `np.random.randint()` | Bilangan bulat acak |
| `np.random.rand()` | Bilangan desimal acak |

---

# Modul 1.2 -- Atribut Array NumPy

Atribut adalah informasi yang dimiliki sebuah objek `ndarray`. Berbeda dengan fungsi (`np.zeros()`, `np.arange()`, dll.), atribut diakses **tanpa tanda kurung**.

## 1. `.ndim`

Menunjukkan jumlah dimensi array.

```python
print(arr.ndim)
```

Output:

> 2

Karena `arr` memiliki 2 dimensi (baris dan kolom).

In [2]:
#Contoh Lain 
a = np.array([1,2,3])
print(a.ndim)

1


---

## 2. `.shape`

Menunjukkan ukuran tiap dimensi.

```python
print(arr.shape)
```

Output:

`(2, 3)`

Artinya :
- 2 baris
- 3 kolom

contoh:

In [3]:
cube = np.zeros((4,5,6))
print(cube.shape)

(4, 5, 6)


---

## 3. `.size`

Jumlah seluruh elemen.

```python
print(arr.size)
```

Output:
`6`

Karena:
`2 x 3 = 6`

contoh:

In [6]:
bos = np.zeros((3, 5, 6))
print(bos.size)

90


---

## 4. `.dtype`

Menunjukkan tipe data elemen.

```python
print(arr.dtype)
```

Output (tergantung sistem):

`int64`

Kalau:

```python
a = np.array([1.5, 2.5])
print(a.dtype)
```

Output:

`float64`

---

## 5. `.itemsize`

Ukuran satu elemen dalam byte.

```python
print(arr.itemsize)
```

Misaalnya menghasilkan :

`8`

Artinya setiap elemen menggunakan 8 byte memori.

Contoh:

In [9]:
print(bos.itemsize)

8


---

## 6. `.nbytes`

Total memori yang dipakai array.

```python
print(arr.nbytes)
```

Output :

`48`

Karena:

`6 elemen × 8 byte = 48 byte`

Contoh:

In [10]:
print(bos.nbytes)

720


---

## Ringkasan

| Atribut | Fungsi |
| --- | --- | 
| .ndim | Jumlah dimensi |
| .shape | Bentuk array |
| .size | Jumlah elemen |
| .dtype | Tipe data |
| .itemsize | Ukuran tiap elemen (byte)) |
| .nbytes | Total Memory Array |

---

# Modul 1.2 (Lanjutan) — Atribut Array NumPy

---
---

## 7. `.T` (Transpose)

Transpose berarti menukar baris dan kolom.

Misalnya:

```python
A = np.array([
    [1,2,3],
    [4,5,6]
])

print(A)
```

Output:

```text
[[1 2 3]
 [4 5 6]]
 ```

Transpose:

```python
print(A.T)
```

Output:

```text
[[1 4]
 [2 5]
 [3 6]]
 ```

 Visualnya:

 ```text
 1 2 3        1 4
4 5 6   →    2 5
              3 6
```

Transpose sangat sering digunakan pada:

- Machine Learning
- Linear Algebra
- Matrix Multiplication

---

## 8. `.real`

Mengambil bagian real dari bilangan kompleks.

Contoh:

```python
a = np.array([1+2j, 3+4j])

print(a.real)
```

Output:

`[1. 3.]`

---

## 9. `.imag`

Mengambil bagian imajiner.

```python
print(a.imag)
```

Output:

`[2. 4.]`

---

## 10. `.flat`

Menghasilkan iterator yang mengakses seluruh elemen array satu per satu.

Misalnya

```python
A = np.array([
    [1,2],
    [3,4]
])

for i in A.flat:
    print(i)
```

Output:

```text
1
2
3
4
```

Berbeda dengan

```python
for i in A:
    print(i)
```

Output:

```text
[1 2]
[3 4]
```

Jadi:
- `A` --> iterasi per baris
- `A.flat` --> iterasi per elemen
---

# Modul 1.3 — Indexing & Slicing NumPy

> **Tujuan Pembelajaran**
>
> Setelah modul ini, kamu mampu:
>
> * Mengakses elemen tertentu pada array 1D dan 2D.
> * Mengambil sebagian data (slicing).
> * Menggunakan indexing dan slicing sebagai dasar manipulasi data di NumPy dan Pandas.

---

# 1. Indexing pada Array 1 Dimensi

Misalkan kita memiliki array:

```python
arr = np.array([10, 20, 30, 40, 50])
```

Posisi setiap elemen:

| Index | Nilai |
| ----: | ----: |
|     0 |    10 |
|     1 |    20 |
|     2 |    30 |
|     3 |    40 |
|     4 |    50 |

Mengambil elemen pertama:

```python
print(arr[0])
```

Output:

```text
10
```

Mengambil elemen keempat:

```python
print(arr[3])
```

Output:

```text
40
```

---

# 2. Negative Index

NumPy juga mendukung index negatif.

| Index | Nilai |
| ----: | ----: |
|    -5 |    10 |
|    -4 |    20 |
|    -3 |    30 |
|    -2 |    40 |
|    -1 |    50 |

Contoh:

```python
print(arr[-1])
```

Output:

```text
50
```

Elemen kedua dari belakang:

```python
print(arr[-2])
```

Output:

```text
40
```

> **Tips Mentor**
>
> Aku sendiri sangat sering menggunakan `[-1]` untuk mengambil elemen terakhir, karena kita tidak perlu mengetahui panjang array terlebih dahulu.

---

# 3. Slicing pada Array 1D

Sintaks dasar:

```python
array[start:stop]
```

> **Perlu diingat:**
>
> * `start` **termasuk** (*inclusive*)
> * `stop` **tidak termasuk** (*exclusive*)

Misalnya:

```python
print(arr[1:4])
```

Output:

```text
[20 30 40]
```

Mengapa?

* Mulai dari index **1** → `20`
* Berhenti **sebelum** index **4**

Sehingga yang diambil adalah:

```text
20 30 40
```

---

## Tanpa `start`

```python
print(arr[:3])
```

Output:

```text
[10 20 30]
```

Artinya mengambil elemen mulai dari index `0` hingga sebelum index `3`.

---

## Tanpa `stop`

```python
print(arr[2:])
```

Output:

```text
[30 40 50]
```

Artinya mengambil elemen mulai dari index `2` hingga elemen terakhir.

---

## Mengambil Seluruh Array

```python
print(arr[:])
```

Output:

```text
[10 20 30 40 50]
```

Teknik ini sering digunakan saat membuat salinan atau melakukan operasi terhadap seluruh array.

---

# 4. Menggunakan `step`

Sintaks lengkap:

```python
array[start:stop:step]
```

Contoh:

```python
print(arr[::2])
```

Output:

```text
[10 30 50]
```

Karena mengambil setiap **2 elemen**.

Contoh lain:

```python
print(arr[1::2])
```

Output:

```text
[20 40]
```

Mulai dari index `1`, lalu melompat setiap `2` elemen.

---

# 5. Membalik Array

Cara paling umum:

```python
print(arr[::-1])
```

Output:

```text
[50 40 30 20 10]
```

### Mengapa bisa?

* `start` dikosongkan → mulai dari akhir.
* `stop` dikosongkan → sampai awal.
* `step = -1` → bergerak mundur satu per satu.

Teknik ini sangat sering digunakan, baik di NumPy maupun Python secara umum.

---

# Ringkasan

| Operasi               | Contoh      |
| --------------------- | ----------- |
| Elemen pertama        | `arr[0]`    |
| Elemen terakhir       | `arr[-1]`   |
| Slice                 | `arr[1:4]`  |
| Sampai index tertentu | `arr[:3]`   |
| Dari index tertentu   | `arr[2:]`   |
| Seluruh array         | `arr[:]`    |
| Setiap 2 elemen       | `arr[::2]`  |
| Membalik array        | `arr[::-1]` |

---

# Modul 1.3 - Indexing & Slicing (Lanjutan/Advanced)

Pada modul ini kita akan belajar mengambil data dengan cara yang jauh lebih fleksibel.

---

## 1. Fancy Indexing

Misalkan:

```python
arr = np.array([10, 20, 30, 40 , 50])
```

Kita bisa mengambil beberapa index sekaligus.

```python
arr[[0, 2, 4]]
```

Output:

```text
array([10, 30, 50])
```

Artinya:

```text
index 0 → 10
index 2 → 30
index 4 → 50
```

Berbeda dengan slicing.

```python
arr[0:5:2]
```

mengambil rentang.

Sedangkan

```python
arr[[0, 2, 4]]
```

mengambil indeks tertentu.

---

## 2. Mengubah banyak Elemen Sekaligus

```python
arr[[1, 3]] = 100
```

Output

```python
array([10, 100, 30, 100, 50])]
```

Tidak perlu mengganti satu-satu.

---

## 3. Boolean Indexing

Ini adalah fitur yang sangat sering dipakai pada Data Science.

Misalkan

```python
arr = np.array([3, 8 ,2, 10, 6])
```

Cari angka yang lebih besar dari 5.

```python
arr > 5
```

Output

```python
array([False, True, False, True, True])
```

Jika dipakai sebagai index

```python
arr[arr > 5]
```

Output

```python
array([8, 10, 6])
```

Konsepnya

```text
3   -> False
8   -> True
2   -> False
10  -> True
6   -> True
```

Yang `True` akan diambil.

---

## 4. Beberapa Kondisi Sekaligus

Misalnya ingin angka di antara 5 dan 15.

```python
arr = np.array([2,7,10,15,20])
```

Gunakan
```python
arr[(arr > 5) & (arr < 15)]
```

Output

```python
array([7, 10])
```

Operator yang digunakan

```text
&   dan (AND)

|   atau (OR)

~   NOT
```

Contoh

```python
arr[(arr < 5) | (arr > 15) ]
```

Output

```python
array([2, 20])
```

---

## 5. Filtering Baris pada Array 2D

```python
arr = np.array([
    [80, 90],
    [50, 60],
    [90, 88]
])
```

Ambil baris yang nilai kolom pertama lebih dari 70

```python
arr[arr[:,0] > 70]
```

Penjelasan

```text
arr[:,0]
```

mengambil kolom pertama

```text
[80, 50, 95]
```

Kemudian dibuat mask 

```text
[True, False, True]
```

Lalu NumPy memilih hanya baris yang bernilai `True`

---

## Kapan teknik ini dipakai?

Di dunia Data Science hampir setiap hari.

Contoh:

- memilih pelanggan umur > 25
- memilih transaksi > Rp1 juta
- memilih data yang kosong
- memilih gambar dengan nilai piksel tertentu
- filtering dataset sebelum Machine Learning

Boolean indexing adalah salah satu kemampuan paling penting di NumPy.

---

# Modul 1.4 — Array Manipulation (Manipulasi Array)

Materi ini sangat penting karena hampir semua pekerjaan data science menggunakan operasi manipulasi array.

## 1. Reshape(`.reshape()`)

Mengubah bentuk array tanpa mengubah datanya.

```python
a = np.arange(12)
print(a)
```

Output

```python
[ 0 1 2 3 4 5 6 7 8 9 10 11]
```

Ubah menjadi matrik 3x4

```python
b = a.reshape(3, 4)
print(b)
```

Output

```text
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
```

---

## 2. Flatten(`.flatten()`)

Mengubah array multidimensi menjadi 1 dimensi.

```python
a = np.array([[1, 2, 3], 
             [4, 5, 6]])
print(a.flatten())
```

Output

```python
[1 2 3 4 5 6]
```

---

## 3. Transpose (`.T`)

Menukar baris menjadi kolom.

```python
a = np.array([[1, 2, 3],
             [4, 5, 6]])
print(a.T)
```

Output

```text
[[1 4]
 [2 5]
 [3 6]]
```

Shape berubah dari `(2,3)`

menjadi `(3,2)`

---

## 4. Resize dengan dimensi otomatis (`-1`)

NumPy bisa menghitung satu dimensi secara otomatis.

```python
a = np.arange(12)
print(a.reshape(2, -1))
```

Output

```text
[[0 1 2 3 4 5]
 [6 7 8 9 10 11]]
```

atau 

```python
print(a.reshape(-1, 3))
```

Output

```text
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [9 10 11]]
```

---

## 5. Perbedaan `reshape()` dan `resize()`

### **reshape()**

Menghasilkan array baru.

```python
a = np.arange(6)

b= a.reshape(2, 3)

print(a)
print(b)
```

Output

```text
[0 1 2 3 4 5]


[[0 1 2]
 [3 4 5]]
```

Array aslinya tetap ada.

---

### **resize()**

Mengubah array asli.

```python
a = np.arange(6)

a.resize((3, 2))

print(a)
```

Output

```text
[[0 1]
 [2 3]
 [4 5]]
```

---

# Ringkasan 

| Fungsi | Kegunaan |
| --- | --- |
| `.reshape()` | Mengubah bentuk array |
| `.flatten()` | Mengubah menjadi 1D  |
| `.T` | Transpose (tukar baris dan kolom) |
| `.reshape(-1, n)`  /  `.reshape(n, -1)` | NumPy menghitung ukuran otomatis |
| `.resize()` | Mengubah ukuran array asli |

---

# NumPy 1.5 — Broadcasting

Broadcasting adalah salah satu konsep paling penting di NumPy. Konsep ini memungkinkan kita melakukan operasi antar array dengan bentuk (shape) yang berbeda tanpa perlu melakukan looping.

---

# Kenapa Broadcasting Penting?

Misalkan kita punya 1000 siswa.

Tanpa broadcasting:

```python
hasil = []

for i in range(len(data)):
    hasil.append(data[i] + 5)
```

Dengan NumPy:

```python
hasil = data + 5
```

Yang terjadi sebenarnya adalah broadcasting.

---

## Contoh 1 — Scalar Broadcasting

```python
a = np.array([1, 2, 3, 4])
print(a + 10)
```

Output

```text
[11 12 13 14]
```

Secara konsep NumPy menganggap:

```text
10
↓
[10 10 10 10]
```

lalu menjumlahkannya.

---

## Contoh 2 — Vector Broadcasting

```python
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([10,20,30])

print(A + B)
```

Output

```text
[[11 22 33]
 [14 25 36]]
```

Yang terjadi:

```text
[10 20 30]
↓

[[10 20 30]
 [10 20 30]]
```

---

## Contoh 3 — Kolom Broadcasting

Misalnya

```python
A = np.array([
    [1,2,3],
    [4,5,6]
])

B = np.array([
    [100],
    [200]
])

print(A + B)
```

Output

```text
[[101 102 103]
 [204 205 206]]
```

Yang terjadi:

```text
[[100]
 [200]]

↓

[[100 100 100]
 [200 200 200]]
```

---

## Aturan Broadcasting

NumPy membandingkan shape **dari belakang.**

Misalnya

```text
(3,4)

(4,)
```

Bandingkan:

```text
3 4
  4
```

Karena dimensi terakhir sama (4), broadcasting berhasil.

---

Contoh lain

```text
(2,3)

(1,3)
```

```text
2 3
1 3
```

Dimensi 1 dapat diperluas menjadi 2.

---

Contoh lain

```text
(5,1)

(1,4)
```

```text
(5, 4)
```

Karena kedua dimensi yang bernilai `1` bisa diperluas.

---

## Kapan Broadcasting Gagal?

Misalnya 

```text
(2,3)

(4,)
```

Bandingkan

```text
2 3
  4
```

Karena

```text
3 ≠ 4
```

dan tidak ada yang bernilai 1, maka muncul error:

```text
ValueError:
operands could not be broadcast together
```

---

## Ringkasan Aturan 

Dua dimensi kompatibel jika:

- Nilai dimensinya sama.
- Salah satunya berdimensi `1`.

Selain itu, broadcasting gagal.

---

## Contoh Nyata

Misalnya data tinggi badan:

```python
tinggi = np.array([165,170,175,180])

tinggi_meter = tinggi / 100
```

Atau menaikkan seluruh gaji:
```python
gaji = np.array([5,7,8,10])

gaji += 2
```

Atau menormalkan gambar RGB:

```python
image = image /255
```

Semuanya memanfaatkan broadcasting.

---

# Ringkasan Materi

| Konsep              | Penjelasan                                                               |
| ------------------- | ------------------------------------------------------------------------ |
| Scalar Broadcasting | Satu angka diterapkan ke seluruh elemen array.                           |
| Vector Broadcasting | Vektor diperluas agar sesuai dengan matriks.                             |
| Column Broadcasting | Kolom diperluas ke seluruh kolom.                                        |
| Aturan              | Broadcasting berhasil jika dimensi sama atau salah satunya bernilai `1`. |
| Error               | Terjadi jika dimensi tidak kompatibel.                                   |

---

# 📘 Modul 1.6 — NumPy Mathematical Operations & Aggregation

> Target kompetensi
> - Memahami operasi matematika pada array.
> - Menggunakan fungsi agregasi untuk analisis data.
> - Mengenal konsep axis pada array 2D.
> - Menyiapkan dasar sebelum masuk ke Pandas.

---

## 1. Operasi Matematika Dasar
Salah satu kelebihan NumPy adalah semua operasi dilakukan secara vectorized, tanpa perlu `for` loop.

```python
import numpy as np

a = np.array([2,4,6,8])
b = np.array([1,2,3,4])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)
```

Output

```text
[ 3  6  9 12]
[1 2 3 4]
[ 2  8 18 32]
[2. 2. 2. 2.]
[ 4 16 36 64]
```

---

## 2. Universal Functions (Ufunc)

NumPy menyediakan banyak fungsi matematika yang bekerja langsung pada seluruh array.

```python
arr = np.array([1,4,9,16])

print(np.sqrt(arr))
```

Output

```text
[1. 2. 3. 4.]
```

Beberapa fungsi yang sering dipakai:

```python
np.sqrt()
np.square()
np.abs()
np.exp()
np.log()
np.sin()
np.cos()
np.tan()
```

Contoh:

```python
arr = np.array([-2,-1,0,1,2])

print(np.abs(arr))
```

Output

```text
[2 1 0 1 2]
```

---

## 3. Fungsi Agregasi 

Misalkan

```python
arr = np.array([5, 8, 10, 12, 15])
```

### Jumlah

```python
np.sum(arr)
```

Output

```text
50
```

---

### Rata-rata

```python
np.mean(arr)
```

Output

```text
10.0
```

---

### Nilai Maksimum

```python
np.max(arr)
```

Output

```text
15
```

---

### Nilai Minimum

```python
np.min(arr)
```

Output

```text
5
```

----

### Standar Deviasi

```python
np.std(arr)
```

Output

```text
3.40587727318528
```

---

### Variansi

```python
np.var(arr)
```

Output

```text
11.6
```

---

## 4. Aggregation pada Matrix

Misalkan

```python
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
```

### Jumlah seluruh elemen

```python
np.sum(matrix)
```

Output

```text
45
```

---

### Jumlah tiap kolom

```python
np.sum(matrix, axis = 0)
```

Output

```text
[12 15 18]
```

Karena:

```text
1+4+7 = 12
2+5+8 = 15
3+6+9 = 18
```

---

### Jumlah tiap baris

```python
np.sum(matrix, axis = 1)
```

Output

```text
[6 15 24]
```

---

## 5. Memahami `axis`

Ini adalah salah satu konsep terpenting di NumPy.

Misalkan:

```python
arr = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]

print(np.sum(arr, axis = 0))
```

### axis = 0

Bekerja ke bawah (per kolom)

```text
↓ ↓ ↓

1
4
7

2
5
8

3
6
9
```

Hasil:

```text
[12 15 18]
```

---

### axis = 1

Bekerja ke samping (per baris)

```text
1 2 3
4 5 6
7 8 9
```

```python
arr = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]

print(np.sum(arr, axis=1))
```

Hasil:

```text
[6 15 24]
```

📌 Tips mengingat:

- `axis=0` → turun per kolom.
- `axis=1` → menyapu per baris.

---

## Ringkasan

Hari ini kamu mempelajari:

- ✅ Operasi matematika antar-array.
- ✅ Universal Functions (`sqrt`, `abs`, `square`, dll.).
- ✅ Fungsi agregasi (`sum`, `mean`, `max`, `min`, `std`, `var`).
- ✅ Penggunaan `axis=0` dan `axis=1`.

---

# Modul 1.6.1 — `argmax()`, `argmin()`, dan Boolean Aggregation

Target setelah modul ini:

- Memahami perbedaan nilai terbesar dan posisi nilai terbesar.
- Menggunakan `np.argmax()` dan `np.argmin()`.
- Menggunakan parameter `axis`.
- Memahami Boolean Aggregation:
  - `np.any()`
  - `np.all()`
- Mengombinasikan semuanya untuk analisis data sederhana.

Materi ini memang kecil, tetapi sangat sering dipakai saat preprocessing data dan machine learning.

---

## `argmax()`

Mislkan kita punya data

```python
nilai = np.array([70, 85, 90, 78])
```

Kalau kita ingin nilai terbesar:

```python
np.max(nilai)
```

Output

```text
90
```

Tetapi kalau kita ingin **posisi** nilai terbesar:

```python
np.argmax(nilai)
```

Output

```
2
```

Karena elemen terbesar merupakan 90 dan berada di indeks ke-2.

Perbedaannya:

| Fungsi | Menghasilkan |
| ------ | ------------ |
| `np.max()` | Nilai terbesar |
| `np.argmax()` | Indeks nilai terbesar |

---

## `argmin()`

Kebalikannya

```python
np.argmin(nilai)
```

Output:

```text
0
```

Karena nilai terkecil (70) terletak di indeks 0.

---

## Menggunakan `axis`

```python
A = np.array([
    [4, 8, 1],
    [6, 2, 9]
])
```

Per kolom:

```python
np.argmax(A, axis = 0)
```

Hasil:

```text
[1 0 1]
```

Artinya:

- Kolom 1 → terbesar di baris 1
- Kolom 2 → terbesar di baris 0
- Kolom 3 → terbesar di baris 1

Per baris:

```python
np.argmax(A, axis = 1)
```

Hasil:

```text
[1 2]
```

Baris pertama → indeks 1 (angka 8)

Baris kedua → indeks 2 (angka 9)

--- 

## Boolean Aggregation

Misalkan 

```python
A = np.array([True, True, False])
```

### `np.any()`

```python
np.any(A)
```

Output

```text
True
```

Karena minimal ada 1 `True`.

### `np.all()`

```python
np.all(A)
```

Output

```text
False
```

Karena tidak semuanya `True`.

---

Contoh Nyata:

```python
nilai = np.array([80, 75, 90, 65])

nilai >= 75
```

Hasil:

```text
[True True True False]
```

Apakah semua lulus?

```python
np.all(nilai >= 75)
```

```text
False
```

Apakah ada yang lulus?

```python
np.any(nilai >= 75)
```

```text
True
```

---

Kapan dipakai?

Contoh kasus:

Dataset suhu:

```python
suhu = np.array([31, 29, 34, 36, 28])
```

Cari hari terpanas:

```python
idx = np.argmax(suhu)
```

lalu:

```python
print(suhu[idx])
```

Hasil:

```text
36
```

Sangat umum dipakai saat mencari:

- skor tertinggi
- probabilitas terbesar
- kelas prediksi model
- error terbesar
- fitur dominan

---

## Ringkasan

- `np.max()` → nilai terbesar
- `np.argmax()` → posisi nilai terbesar
- `np.min()` → nilai terkecil
- `np.argmin()` → posisi nilai terkecil
- `np.any()` → ada minimal satu `True`
- `np.all()` → semua bernilai `True`

---

# 📚 Modul NumPy — Sorting & Searching

---

##🎯 Tujuan Pembelajaran

Setelah menyelesaikan modul ini, kamu akan mampu:

- Mengurutkan array NumPy.
- Mengurutkan berdasarkan baris atau kolom.
- Mendapatkan indeks hasil pengurutan.
- Mencari elemen berdasarkan kondisi.
- Menemukan nilai unik beserta jumlah kemunculannya.
- Menggunakan fungsi searching untuk analisis data.

---

## 1. Sorting dengan `np.sort()`

Fungsi paling dasar untuk mengurutkan array.

```python
import numpy as np

arr = np.array([5, 2, 8, 1, 7])

hasil = np.sort(arr)

print(hasil)
```

Output

```text
[1 2 5 7 8]
```

Hal penting

`np.sort()` tidak mengubah array asli, tetapi membentuk array baru berdasarkan array asli yang sudah diurutkan.

```python
print(arr)
```

Output

```text
[5 2 8 1 7]
```

---

## 2. Sorting dengan `array.sort()`

Berbeda dengan sebelumnya

```python
arr = np.array([5, 2, 8, 1, 7])

arr.sort()

print(arr)
```

Output

```text
[1 2 5 7 8]
```

Sekarang array aslinya berubah.

### Perbedaan keduanya 

| `np.sort()` | `array.sort()` |
| ---------- | ------------- |
| Mengembalikan array baru | Mengubah array asli |
| Original tetap | Original berubah |

---

## 3. Sorting array 2D

Misalnya

```python
arr = np.array([
    [3, 1, 2],
    [9, 5, 7]
])
```

Output

```text
[[3 1 2]
 [9 5 7]]
```

---

### axis = 1 (default)

```python
np.sort(arr, axis = 1)
```

Output

```text
[[1 2 3]
 [5 7 9]]
```

Artinya:

Setiap **baris** diurutkan sendiri-sendiri.

---

### axis = 0

```python
np.sort(arr, axis = 0)
```

Output

```text
[[3 1 2]
 [9 5 7]]
```

Contoh ini memang belum terlihat berubah karena setiap kolom sudah berurutan. Agar lebih jelas:

```python
arr = np.array([
    [9,4,7],
    [3,8,1]
])

print(np.sort(arr, axis=0))
```

Output

```text
[[3 4 1]
 [9 8 7]]
```

Setiap **kolom** diurutkan dari atas ke bawah.

---

## Ringkasan Bagian 1
- `np.sort()` → membuat array baru.
- `array.sort()` → mengubah array asli.
- `axis=1` → urut per baris.
- `axis=0` → urut per kolom.

---

🧠 Tips Mengingat

Bayangkan array sebagai tabel Excel:

- axis = 0 → bergerak **vertikal** (kolom).
- axis = 1 → bergerak **horizontal** (baris).

---

## 4. `np.argsort()`

### Apa itu `bp.argsort()`?

Kalau `np.sort()` mengembalikan nilai yang sudah diurutkan, maka `np.argsort()` mengembalikan indeks yang menunjukkan urutan data setelah di-sort.

Dengan kata lain:

- `np.sort()` → menghasilkan array yang sudah terurut.
- `np.argsort()` → menghasilkan posisi (index) elemen-elemen tersebut.

---

### Contoh 1

```python
arr = np.array([40, 10 ,30 , 20])

print(np.sort(arr))
```

Output

```text
[10 20 30 40]
```

Sekarang gunakan `argsort()`.

```python
print(np.argsort(arr))
```

Output

```text
[1 3 2 0]
```

Mengapa hasilnya seperti itu?

Array awal

| Index | Nilai |
| ----: | ----: |
|     0 |    40 |
|     1 |    10 |
|     2 |    30 |
|     3 |    20 |

Setelah diurutkan menjadi 

```text
10 20 30 40
```

Nili tersebut berasal dari index 

```text
1 3 2 0
```

Itulah yang dikembalikan `argsort()`.

---

### Contoh 2

Mengurutkan array menggunakan indeks dari `argsort()`.

```python
arr = np.array([40, 10, 30, 20])

idx = np.argsort(arr)

print(idx)
print(arr[idx])
```

Output

```text
[1 3 2 0]

[10 20 30 40]
```

Disini terjadi proses:

```text
arr[idx]

↓

arr[[1,3,2,0]]

↓

[10,20,30,40]
```

---

### Contoh 3

Data nilai siswa.

```python
nama = np.array([
    "Andi",
    "Budi",
    "Citra",
    "Doni"
])

nilai = np.array([
    80,
    95,
    70,
    85
])

idx = np.argsort(nilai)

print(nama[idx])
print(nilai[idx])
```

Output

```python
['Citra' 'Andi' 'Doni' 'Budi']

[70 80 85 95]
```

Ini sangat berguna ketika ada dua array yang saling berhubungan.

---

### Kapan np.argsort() digunakan?

Biasanya dipakai ketika ingin:

- ✅ Mengurutkan data tanpa mengubah array asli.
- ✅ Mengurutkan beberapa array sekaligus berdasarkan satu array.
- ✅ Mencari ranking.
- ✅ Mengurutkan dataset pada Data Science.

Contohnya:

```text
Nama  ← ikut berpindah
Nilai ← dijadikan acuan sorting
```

---

### Perbedaan `sort()` dan `argsort()`

| Fungsi         | Mengembalikan               |
| -------------- | --------------------------- |
| `np.sort()`    | Nilai yang sudah diurutkan  |
| `np.argsort()` | Indeks urutan hasil sorting |


Contoh:

```text
Array

[40 10 30 20]

np.sort()

↓

[10 20 30 40]

np.argsort()

↓

[1 3 2 0]
```

---

## 💡 Ringkasan
- `np.sort()` → menghasilkan nilai yang telah diurutkan.
- `np.argsort()` → menghasilkan indeks urutan.
- Sangat berguna untuk ranking, sorting banyak array, dan Data Science.

---

# 📖 Lesson 6 — Ascending vs Descending Sort

##🎯 Tujuan Pembelajaran

Setelah materi ini kamu akan mampu:

- Memahami bahwa `np.sort()` secara default mengurutkan ascending.
- Melakukan descending **sort** dengan beberapa teknik.
- Memilih teknik yang paling efisien sesuai kebutuhan.

---

## 1. Ascending Sort (Default)

Secara default, `np.sort()` menggunakan dari kecil → besar.

```python
import numpy as np

arr = np.array([7, 2, 9, 1, 5])

print(np.sort(arr))
```

Output

```text
[1 2 5 7 9]
```

Urutannya:

```text
[1 2 5 7 9]
```

Tidak perlu memberi parameter apapun.

---

## 2. Descending Sort

NumPy **tidak memiliki** parameter seperti:

```python
np.sort(arr, reverse=True)
```

Kode di atas **tidak ada** di NumPy.

Sebagai gantinya kita menggunakan teknik tertentu.

---

### Cara 1 — Reverse setelah sort (Paling umum)

```python
arr = np.array([7,2,9,1,5])

descending = np.sort(arr)[::-1]

print(descending)
```

Output

```python
[9 7 5 2 1]
```

Prosesnya:

```text
Array asli

7 2 9 1 5

↓

Sort

1 2 5 7 9

↓

Reverse menggunakan step (-1)

9 7 5 2 1
```

`[::-1]` berarti membaca array dari belakang kedepan.

---

### Cara 2 — Menggunakan Negative

Jika datanya numerik:

```python
descending = -np.sort(-arr)
```

Contoh

```python
arr = np.array([7, 2, 9, 1, 5])

print(-np.sort(-arr))
```

Output

```text
[9 7 5 2 1]
```

Logikanya:

```text
7 2 9 1 5

↓

-7 -2 -9 -1 -5

↓

Sort

-9 -7 -5 -2 -1

↓

Kalikan -1 lagi

9 7 5 2 1
```

Teknik ini cukup sering muncul di kode ilmiah.

---

### Cara 3 — Descending dengan argsort()

Misalnya

```python
arr = np.array([7,2,9,1,5])

idx = np.argsort(arr)[::-1]

print(idx)
```

Output

```text
[2 0 4 1 3]
```

Kalau dipakai:

```python
print(arr[idx])
```

Output

```text
[9 7 5 2 1]
```

Ini sangat berguna ketika kita ingin mengurutkan **indeks**, bukan hanya nilainya.

---

### Perbandingan

Misalkan

```python
arr = np.array([40, 10, 30, 20])
```

Ascending

```python
np.sort(arr)
```

```text
10 20 30 40
```

Descending

```python
np.sort(arr)[::-1]
```

```text
40 30 20 10
```

Index Descending

```python
np.argsort(arr)[::-1]
```

```text
0 2 3 1
````

---

## Ringkasan 

| Operasi                 | Kode                    |
| ----------------------- | ----------------------- |
| Ascending               | `np.sort(arr)`          |
| Descending              | `np.sort(arr)[::-1]`    |
| Descending (alternatif) | `-np.sort(-arr)`        |
| Indeks Ascending        | `np.argsort(arr)`       |
| Indeks Descending       | `np.argsort(arr)[::-1]` |


---